apiVersion: v1
kind: Pod
metadata:
  name: zimbra
spec:
 containers:
    - name: zimbra
      image: roselroa/myzimbra-auto:latest
      ports:
      - containerPort: 443
        protocol: TCP
      env:
      - name: EXT_DOMAIN
        value: k0l0s0s.net
      - name: EXT_HOST
        value: zimbra
      - name: PASSWORD
        value: temp1234
 imagePullSecrets:
    - name: regsecret
