apiVersion: v1
kind: Pod
metadata:
  name: zimbra
spec:
 hostname: zimbra
 subdomain: company1
 containers:
    - name: zimbra
      image: roselroa/myzimbra-auto:latest
      ports:
      - containerPort: 443
        protocol: TCP
      securityContext:
        privileged: true
      env:
      - name: PASSWORD
        value: temp1234
 imagePullSecrets:
    - name: regsecret
