apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: zimbra
  name: zimbra
  selfLink: /api/v1/namespaces//services/zimbra
spec:
  deprecatedPublicIPs:
  - 192.168.64.2
  externalIPs:
  - 192.168.64.2
  ports:
  - name: port-1
    port: 7071
    protocol: TCP
    targetPort: 7071
  - name: port-2
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: zimbra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
